### ISSUE TITLE
<html> element

### ISSUE THREAD

**Issue by aubreywullschleger** [lwmmccluskey/prj-rev-bwfs-dasmoto#1]
Important for errors! Only a `<head>` element and `<body>` element are allowed to be nested inside of the `<html>` element.  Here you have a heading (`<h1>`) element nested inside the `<html>` element.  Instead, you'll want to move the `<h1>` element to the top of the `<body>` element.  See here for more info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html

https://github.com/lwmmccluskey/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/home.html#L7-L8

**Comment by lwmmccluskey** [comment]
Thanks

**Comment by lwmmccluskey** [comment]
Thanks
