### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [lwmmccluskey/prj-rev-bwfs-dasmoto#6]
Grade: Meets expectations

Summary:
Great work on this first project! I like your consistent nesting and indentation in the HTML, and your used of comments in your HTML.

A few things to work on here would be: 1. nesting your elements correctly, 2. using  descriptive `alt` attributes on your `<img>` elements, and 2. using group selectors for repeated styles in your CSS.

Next, I challenge you to research and implement media queries to make your page responsive for all screen widths. This is a challenge I think you are ready for based on your work with this project! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by lwmmccluskey** [comment]
Thanks
